name: Build Android

on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm32", "aarch64", "x86_64", "i686" ]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:
      - name: Disable symlinks in git config
        run: git config --global core.symlinks false
        
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt update
          sudo apt install -y meson libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev
          pip3 install mako
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          envsubst <android-drm-${{matrix.arch}} >build-crossfile
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/drm.git
          cd drm
          meson setup "build-android" \
            --prefix=/tmp/drm-static \
            --cross-file "../build-crossfile" \
            -Ddefault_library=static \
            -Dintel=disabled \
            -Dradeon=disabled \
            -Damdgpu=disabled \
            -Dnouveau=disabled \
            -Dvmwgfx=disabled \
            -Dfreedreno=enabled \
            -Dvc4=disabled \
            -Detnaviv=disabled \
            -Dfreedreno-kgsl=true
          ninja -C "build-android" install
          envsubst <android-${{matrix.arch}} >build-crossfile
          cd ..
          meson setup "build-android" \
            --prefix=/tmp/zink \
            --cross-file "build-crossfile" \
            -Dplatforms=android \
            -Dplatform-sdk-version=25 \
            -Dandroid-stub=true \
            -Dllvm=disabled \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dgbm=disabled \
            -Dglx=disabled \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=swrast,zink,virgl \
            -Dshared-glapi=false
          ninja -C "build-android" install
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: libzink_${{matrix.arch}}
          path: /tmp/zink
